[package]
name = "day-11"
version = "0.1.0"
edition = "2021"
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
common = { version = "0.1.0", path = "../../common" }
